name: Release to HACS

on:
  push:
    tags:
      - 'v*'  # Déclenche l'action tag commençant par "v"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            *
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is an automated release of the latest version of the project.
